from django.conf.urls import url
from django.contrib import admin
from LabaUD import views



urlpatterns = [
    url(r'^index$', views.index),
    url(r'^mainmenu$', views.mainmenu, name='mainmenu'),
    url(r'^failed$', views.failed_my, name='failed'),
    url(r'^mainmenu/PC/outpc$', views.outpc, name='out_pc'),
    url(r'^mainmenu/PC/addpc$', views.addpc_form, name='add_pc'),
    url(r'^mainmenu/PC/editpcform/(?P<pc_name>[\w-]+)$', views.editpc_form, name='edit_pc'),
    url(r'^mainmenu/PC/deletepc/(?P<pc_name>[\w-]+)$', views.deletepc, name='delete_pc'),
    url(r'^mainmenu/Disc/outdisc$', views.outdisc, name='out_disc'),
    url(r'^mainmenu/Disc/adddisc$', views.adddisc_form, name='add_disc'),
    url(r'^mainmenu/Disc/editdiscform/(?P<disc_name>[\w-]+)$', views.editdisc_form, name='edit_disc'),
    url(r'^mainmenu/Disc/deletedisc/(?P<disc_name>[\w-]+)$', views.deletedisc, name='delete_disc'),
    url(r'^mainmenu/Client/outclient$', views.outclient, name='out_client'),
    url(r'^mainmenu/Client/addclient$', views.addclient_form, name='add_client'),
    url(r'^mainmenu/Client/editclientform/(?P<client_name>[\w-]+)$', views.editclient_form, name='edit_client'),
    url(r'^mainmenu/Client/deleteclient/(?P<client_name>[\w-]+)$', views.deleteclient, name='delete_client'),
    url(r'^mainmenu/Rest/outrest$', views.outrest, name='out_rest'),
    url(r'^mainmenu/Rest/addrest$', views.addrest_form, name='add_rest'),
    url(r'^mainmenu/Rest/editrestform/(?P<rest_name>[\w-]+)$', views.editrest_form, name='edit_rest'),
    url(r'^mainmenu/Rest/deleterest/(?P<rest_name>[\w-]+)$', views.deleterest, name='delete_rest'),
    url(r'^mainmenu/Sera/outsera$', views.outsera, name='out_sera'),
    url(r'^mainmenu/Sera/addsera$', views.addsera_form, name='add_sera'),
    url(r'^mainmenu/Sera/editseraform/(?P<sera_name>[\w-]+)$', views.editsera_form, name='edit_sera'),
    url(r'^mainmenu/Sera/deletesera/(?P<sera_name>[\w-]+)$', views.deletesera, name='delete_sera'),
    url(r'^mainmenu/Worker/outworker$', views.outworker, name='out_worker'),
    url(r'^mainmenu/Worker/addworker$', views.addworker_form, name='add_worker'),
    url(r'^mainmenu/Worker/editworkerform/(?P<worker_name>[\w-]+)$', views.editworker_form, name='edit_worker'),
    url(r'^mainmenu/Worker/deleteworker/(?P<worker_name>[\w-]+)$', views.deleteworker, name='delete_worker'),
    url(r'^mainmenu/Work/outwork$', views.outwork, name='out_work'),
    url(r'^mainmenu/Work/addwork$', views.addwork_form, name='add_work'),
    url(r'^mainmenu/Work/editworkform/(?P<work_name>[\w-]+)$', views.editwork_form, name='edit_work'),
    url(r'^mainmenu/Work/deletework/(?P<work_name>[\w-]+)$', views.deletework, name='delete_work'),
    url(r'^mainmenu/Compl/outcompl$', views.outcompl, name='out_compl'),
    url(r'^mainmenu/Compl/addcompl$', views.addcompl_form, name='add_compl'),
    url(r'^mainmenu/Compl/editcomplform/(?P<compl_name>[\w-]+)$', views.editcompl_form, name='edit_compl'),
    url(r'^mainmenu/Compl/deletecompl/(?P<compl_name>[\w-]+)$', views.deletecompl, name='delete_compl'),
    url(r'^mainmenu/Supp/outsupp$', views.outsupp, name='out_supp'),
    url(r'^mainmenu/Supp/addsupp$', views.addsupp_form, name='add_supp'),
    url(r'^mainmenu/Supp/editsuppform/(?P<supp_name>[\w-]+)$', views.editsupp_form, name='edit_supp'),
    url(r'^mainmenu/Supp/deletesupp/(?P<supp_name>[\w-]+)$', views.deletesupp, name='delete_supp'),
    url(r'^mainmenu/Stor/outstor$', views.outstor, name='out_stor'),
    url(r'^mainmenu/Stor/addstor$', views.addstor_form, name='add_stor'),
    url(r'^mainmenu/Stor/editstorform/(?P<stor_name>[\w-]+)$', views.editstor_form, name='edit_stor'),
    url(r'^mainmenu/Stor/deletestor/(?P<stor_name>[\w-]+)$', views.deletestor, name='delete_stor'),
    url(r'^mainmenu/Como/outcomo$', views.outcomo, name='out_como'),
    url(r'^mainmenu/Como/addcomo$', views.addcomo_form, name='add_como'),
    url(r'^mainmenu/Como/editcomoform/(?P<como_name>[\w-]+)$', views.editcomo_form, name='edit_como'),
    url(r'^mainmenu/Como/deletecomo/(?P<como_name>[\w-]+)$', views.deletecomo, name='delete_como'),
    url(r'^mainmenu/Orse/outorse$', views.outorse, name='out_orse'),
    url(r'^mainmenu/Orse/addorse$', views.addorse_form, name='add_orse'),
    url(r'^mainmenu/Orse/editorseform/(?P<orse_name>[\w-]+)$', views.editorse_form, name='edit_orse'),
    url(r'^mainmenu/Orse/deleteorse/(?P<orse_name>[\w-]+)$', views.deleteorse, name='delete_orse'),
    url(r'^mainmenu/Order/outorder$', views.outorder, name='out_order'),
    url(r'^mainmenu/Order/addorder$', views.addorder_form, name='add_order'),
    url(r'^mainmenu/Order/editorderform/(?P<order_name>[\w-]+)$', views.editorder_form, name='edit_order'),
    url(r'^mainmenu/Order/deleteorder/(?P<order_name>[\w-]+)$', views.deleteorder, name='delete_order'),
    url(r'^login$', views.login_my, name='login'),
    url(r'^logout$', views.logout_my, name='logout'),
]
