# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('fio_client', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Compl',
            fields=[
                ('id_compl', models.AutoField(primary_key=True, serialize=False)),
                ('compl_name', models.CharField(max_length=64)),
                ('compl_article', models.CharField(max_length=20)),
                ('compl_price', models.IntegerField()),
                ('compl_maker', models.CharField(max_length=64)),
                ('compl_description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Compl_order',
            fields=[
                ('id_compl_order', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField()),
                ('amount_compl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('bonuses', models.IntegerField()),
                ('reception_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('sum_order', models.IntegerField()),
                ('date_order', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordering_services',
            fields=[
                ('id_ordering_services', models.AutoField(primary_key=True, serialize=False)),
                ('work_price', models.IntegerField()),
                ('note_ordering_services', models.CharField(max_length=128)),
                ('compl_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Compl_order')),
            ],
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id_pc', models.AutoField(primary_key=True, serialize=False)),
                ('description_pc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Receiving_transfer',
            fields=[
                ('id_receivingtransfer', models.AutoField(primary_key=True, serialize=False)),
                ('date_receive', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Client')),
                ('pc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Pc')),
            ],
        ),
        migrations.CreateModel(
            name='Service_adress',
            fields=[
                ('id_service_adress', models.AutoField(primary_key=True, serialize=False)),
                ('service_adress', models.CharField(max_length=128)),
                ('phone_number_adress', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_store_compl', models.AutoField(primary_key=True, serialize=False)),
                ('stock_balance', models.IntegerField()),
                ('compl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Compl')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=128)),
                ('supplier_contact', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id_work', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=128)),
                ('work_name', models.CharField(max_length=64)),
                ('work_term', models.CharField(max_length=128)),
                ('work_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=64)),
                ('phone_number_worker', models.CharField(max_length=13)),
                ('account_number_worker', models.CharField(max_length=20)),
                ('passport_worker', models.CharField(max_length=128)),
                ('dofb_worker', models.DateField()),
                ('fio_worker', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Supplier'),
        ),
        migrations.AddField(
            model_name='ordering_services',
            name='work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Work'),
        ),
        migrations.AddField(
            model_name='ordering_services',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Worker'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordering_services_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Ordering_services'),
        ),
        migrations.AddField(
            model_name='order',
            name='receivingtransfer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Receiving_transfer'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_adress_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Service_adress'),
        ),
        migrations.AddField(
            model_name='compl_order',
            name='store_compl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Storage'),
        ),
        migrations.AddField(
            model_name='client',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabaUD.Discount'),
        ),
    ]
